services:
  - type: web
    name: my-django-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    plan: free
    region: oregon
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: 'False'
