# Generated by Django 4.2.11 on 2024-05-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subofsub',
            old_name='category',
            new_name='sub_category',
        ),
    ]
