# Generated by Django 4.2.11 on 2024-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_category_subofsub_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='TeakWood', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Brown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='Made in India', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default='100 % Teakwood', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='Teak', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_box',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by',
            field=models.CharField(default='Teak Wood Factory', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(default=2),
        ),
    ]
