# Generated by Django 4.2.13 on 2024-06-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
