# Generated by Django 4.2.11 on 2024-05-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Custom Banner Name', 'verbose_name_plural': 'Custom Banner Names'},
        ),
    ]
